# Generated by Django 4.0 on 2021-12-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraiseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_histories', to='auth.user')),
                ('to_who', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recv_histories', to='auth.user')),
            ],
        ),
    ]
